# DATABASE
url=jdbc:sqlserver://localhost:1433;databaseName=BasaltHouseDB;trustServerCertificate=true
userID=sa
password=123456


# JWT
jwt.secret=80fd7e25efc3ad0ef599e1834eff36616150e15be64aecc484466ce6d8ce6c21

# API KEY
google.clientId=565461015648-nbmj341o8na75tomsm7f8gigu0jjqq07.apps.googleusercontent.com
google.clientSecret=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
google.redirectUri=http://localhost:8080/basaltHouseSystem/google-login
google.authUrl=https://accounts.google.com/o/oauth2/v2/auth
google.tokenUrl=https://oauth2.googleapis.com/token
google.userInforUrl=https://www.googleapis.com/oauth2/v3/userinfo

#EMAIL
email.username=kayt1206.js@gmail.com
email.password=ymyneglodcakfloo
#CLOUDINARY
cloudinary.cloudName=dtm81bdmx
cloudinary.apiKey=453729527823794
cloudinary.apiSecret=YCE44fQ2gcG340kQ1J5h0vb4D64
