# DATABASE
url=jdbc:sqlserver://localhost:1433;databaseName=BasaltHouseDB;trustServerCertificate=true
userID=sa
password=123456


# JWT
jwt.secret=edb28e69d8c045c5848ffd739c1f45da884378e9ff536f218d7097bfef093323

# API KEY
google.apikey=YOUR_API_KEY
