# DATABASE
url=jdbc:sqlserver://localhost:1433;databaseName=BasaltHouseDB;trustServerCertificate=true
userID=sa
password=123


# JWT
jwt.secret=80fd7e25efc3ad0ef599e1834eff36616150e15be64aecc484466ce6d8ce6c21

# API KEY
google.apikey=YOUR_API_KEY

#EMAIL
email.username=kayt1206.js@gmail.com
email.password=ymyneglodcakfloo